name: Bot discord

on:
  workflow_dispatch:

jobs:
  update_symbol_list:
    name: Update S&P500 symbol list periodically
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r requirements.txt


      - name: Run Script
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          MYSQL_HOST: 192.168.18.8
          MYSQL_PORT: 3306
          MYSQL_USER: daniel
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        run: |
          python discord_testes.py
